<?php

/**
 * @file
 * The BLP Flex Groups Core.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\row\EntityRow;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Url;
use Drupal\blp_flex_groups\EntityAccessHelper;
use Drupal\node\NodeInterface;

/**
 * Provide a helper function to check for entity reference.
 *
 * @param int $group_id
 *   The group id.
 */
function blp_flex_groups_get_referenced_group($group_id) {

  $field_available = FALSE;

  if (blp_flex_groups_check_for_field_in_bundle()) {

    $result = \Drupal::entityQuery('group')
    ->condition('type', 'blp_event')
    ->condition('field_group_blp_project', $group_id)
    ->execute();

    if ($result) {
      $field_available = TRUE;
    }
    
  }

  return $field_available;

}

/**
 * Check if a bundle holds a certain field.
 */
function blp_flex_groups_check_for_field_in_bundle($entity_type = 'group', $bundle = 'blp_event', $field_name = 'field_group_blp_project') {
  $all_bundle_fields = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity_type, $bundle);
  return isset($all_bundle_fields[$field_name]);
}

